const data = [
  {
    id: 1,
    name: "John Doe",
    job: "Web Developer",
    img: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "I'm a passionate web developer with a keen interest in creating user-friendly and innovative web experiences. In my free time, I enjoy cycling and exploring new trends in technology.",
  },
  {
    id: 2,
    name: "Jane Smith",
    job: "Graphic Designer",
    img: "https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a graphic designer, I specialize in creating visually stunning designs that captivate audiences. I draw inspiration from various art forms and always strive to push the boundaries of creativity.",
  },
  {
    id: 3,
    name: "Michael Johnson",
    job: "Data Scientist",
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=2788&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "My passion lies in uncovering insights from data and using them to drive strategic decisions. I thrive on solving complex problems and am dedicated to staying at the forefront of data science innovations.",
  },
  {
    id: 3,
    name: "Michael Johnson",
    job: "Data Scientist",
    img: "https://images.unsplash.com/photo-1552058544-f2b08422138a?q=80&w=2799&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "My passion lies in uncovering insights from data and using them to drive strategic decisions. I thrive on solving complex problems and am dedicated to staying at the forefront of data science innovations.",
  },
  {
    id: 5,
    name: "David Wilson",
    job: "Software Engineer",
    img: "https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=2786&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "I'm a software engineer with a passion for building scalable and efficient solutions. I enjoy tackling challenging problems and am always eager to learn new technologies.",
  },
  {
    id: 6,
    name: "Jessica Lee",
    job: "UX Designer",
    img: "https://images.unsplash.com/photo-1491349174775-aaafddd81942?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a UX designer, I am passionate about creating intuitive and delightful user experiences. I believe in putting the user at the center of everything I design and constantly seek feedback to improve.",
  },
  {
    id: 7,
    name: "Alexandra Martinez",
    job: "Content Writer",
    img: "https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?q=80&w=2952&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a content writer, I am dedicated to crafting engaging and informative content that resonates with audiences. I enjoy exploring diverse topics and love the challenge of turning ideas into compelling stories.",
  },
  {
    id: 8,
    name: "Christopher Garcia",
    job: "Financial Analyst",
    img: "https://images.unsplash.com/photo-1500048993953-d23a436266cf?q=80&w=2938&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a financial analyst, I specialize in analyzing financial data to provide valuable insights and recommendations. I am detail-oriented and thrive in fast-paced environments where precision is key.",
  },
  {
    id: 9,
    name: "Sarah Thompson",
    job: "Product Manager",
    img: "https://images.unsplash.com/photo-1504593811423-6dd665756598?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a product manager, I am passionate about creating products that solve real-world problems and deliver exceptional user experiences. I enjoy collaborating with cross-functional teams and thrive in dynamic environments.",
  },
  {
    id: 10,
    name: "Ryan Hernandez",
    job: "Sales Representative",
    img: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a sales representative, I am committed to delivering outstanding customer service and building strong relationships with clients. I thrive in fast-paced environments and enjoy the challenge of meeting and exceeding sales targets.",
  },
  {
    id: 11,
    name: "Melissa Taylor",
    job: "HR Manager",
    img: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=2861&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As an HR manager, I am dedicated to fostering a positive work culture and ensuring the well-being of employees. I believe in building diverse and inclusive teams and am passionate about supporting professional growth.",
  },
  {
    id: 12,
    name: "Daniel Rodriguez",
    job: "Architect",
    img: "https://images.unsplash.com/photo-1593104547489-5cfb3839a3b5?q=80&w=2906&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As an architect, I am passionate about creating spaces that inspire and enrich the lives of people. I believe in sustainable design principles and strive to integrate innovation and functionality into every project.",
  },
  {
    id: 13,
    name: "Olivia Lewis",
    job: "Fashion Designer",
    img: "https://images.unsplash.com/photo-1542206395-9feb3edaa68d?q=80&w=2580&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a fashion designer, I am inspired by the intersection of art and culture. I strive to create clothing that is both stylish and sustainable, with a focus on quality craftsmanship and attention to detail.",
  },
  {
    id: 14,
    name: "Lucas Martinez",
    job: "Photographer",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a photographer, I am passionate about capturing moments that evoke emotion and tell a story. I specialize in portrait and landscape photography and am constantly exploring new techniques to push the boundaries of creativity.",
  },
  {
    id: 15,
    name: "Sophia Clark",
    job: "Event Planner",
    img: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As an event planner, I am dedicated to creating unforgettable experiences that leave a lasting impression. I thrive in high-pressure environments and enjoy the challenge of bringing creative visions to life.",
  },
  {
    id: 16,
    name: "Ethan Scott",
    job: "UI Designer",
    img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a UI designer, I am passionate about creating visually appealing and intuitive interfaces that enhance user experiences. I believe in the power of design to solve complex problems and simplify interactions.",
  },
  {
    id: 17,
    name: "Isabella Hall",
    job: "Copywriter",
    img: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a copywriter, I am passionate about crafting compelling narratives that resonate with audiences and drive action. I specialize in creating content that communicates brand messages effectively across various channels.",
  },
  {
    id: 18,
    name: "Nathan Phillips",
    job: "SEO Specialist",
    img: "https://images.unsplash.com/photo-1554727242-741c14fa561c?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As an SEO specialist, I am dedicated to optimizing digital content and improving online visibility. I stay up-to-date with industry trends and best practices to ensure the success of digital marketing strategies.",
  },
  {
    id: 19,
    name: "Madison King",
    job: "Digital Marketer",
    img: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?q=80&w=2592&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a digital marketer, I am passionate about leveraging data and analytics to drive strategic marketing decisions. I specialize in creating integrated campaigns that engage audiences and drive business growth.",
  },
  {
    id: 20,
    name: "Gabriel Adams",
    job: "Video Editor",
    img: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a video editor, I am dedicated to creating visually stunning and engaging content that captivates audiences. I am proficient in various editing software and always strive to push the boundaries of creativity.",
  },
  {
    id: 21,
    name: "Ava Turner",
    job: "Social Media Manager",
    img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=2864&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    text: "As a social media manager, I am passionate about building and engaging communities through strategic content and creative campaigns. I stay up-to-date with the latest social media trends and algorithms to drive meaningful engagement.",
  },
];

export default data;
